packages:
  - 'packages/*'
  - '!examples/gen-ai'
  - '!examples/orama-search-box'
  - 'examples/counter'
  - 'examples/custom-element'
  - '!examples/e-commerce'
  - 'examples/empty'
  - 'examples/random-quote'